"""Coaching guidance per error / success field."""
ERROR_GUIDANCE = {
    'Doble_Falta': {'weakness': 'Las dobles faltas están penalizando demasiado el arranque del punto.',
                    'improvement': 'Trabajar una rutina estable de saque y un segundo servicio con más margen.'},
    'Resto_Derecha_Fallado': {'weakness': 'El resto de derecha está fallando más de lo deseable.',
                              'improvement': 'Ajustar la preparación temprana y priorizar un resto profundo y seguro.'},
    'Resto_Reves_Fallado': {'weakness': 'El resto de revés aparece como foco de error.',
                            'improvement': 'Entrenar lectura del saque al revés y simplificar objetivos.'},
    'Globo_Malo': {'weakness': 'Los globos malos están devolviendo la iniciativa al rival.',
                   'improvement': 'Subir margen sobre la red y trabajar más profundidad.'},
    'Error_Fondo_Derecha': {'weakness': 'La derecha desde el fondo genera pérdida de estabilidad.',
                            'improvement': 'Priorizar trayectorias seguras y mejor selección de altura.'},
    'Error_Fondo_Reves': {'weakness': 'El revés de fondo deja errores no forzados que dañan la consistencia.',
                          'improvement': 'Trabajar control de revés, tiempos de impacto y decisiones más conservadoras.'},
    'Bajada_Derecha_Error': {'weakness': 'La bajada de derecha está apareciendo como foco claro de error.',
                             'improvement': 'Trabajar lectura de rebote, distancia al impacto y terminación simple.'},
    'Bajada_Reves_Error': {'weakness': 'La bajada de revés genera fallos no forzados.',
                           'improvement': 'Entrenar bajada de revés con objetivos amplios y control del plano.'},
    'Posicionamiento_Fondo_Error': {'weakness': 'El posicionamiento en fondo provoca errores por mala distancia.',
                                    'improvement': 'Ajustar recuperaciones al centro y timing de colocación.'},
    'Error_Volea_Derecha': {'weakness': 'La volea de derecha no consolida la ventaja ofensiva en la red.',
                            'improvement': 'Ajustar pasos previos, distancia al impacto y objetivos más amplios.'},
    'Error_Volea_Reves': {'weakness': 'La volea de revés es un punto vulnerable.',
                          'improvement': 'Reforzar estabilidad de muñeca y control direccional.'},
    'Posicionamiento_Volea_Error': {'weakness': 'El posicionamiento en volea no sostiene la red.',
                                    'improvement': 'Trabajar distancia a la red, orientación corporal y pasos.'},
    'Tirar_Ficha_Error': {'weakness': 'La toma de decisión al tirar ficha es demasiado aleatoria.',
                          'improvement': 'Reducir decisiones de alto riesgo y entrenar patrones tácticos claros.'},
    'Bandeja_Error': {'weakness': 'La bandeja o víbora no sostiene la ventaja de red.',
                      'improvement': 'Trabajar contacto alto, dirección segura y elección fina de potencia.'},
    'Smash_Error': {'weakness': 'Los remates fallidos están desperdiciando oportunidades de cierre.',
                    'improvement': 'Mejorar selección del smash y bajar potencia cuando no haya cierre claro.'},
}

SUCCESS_GUIDANCE = {
    'Winner_Derecha': 'La derecha ganadora cierra puntos desde el fondo con criterio.',
    'Winner_Reves': 'El revés ganador aporta desequilibrio y resolución cuando se acelera con criterio.',
    'Resto_Ganador_Derecha': 'El resto ganador de derecha genera ventaja inmediata desde la devolución.',
    'Resto_Ganador_Reves': 'El resto ganador de revés castiga muy bien el servicio rival.',
    'Globo_De_Oro': 'El globo de oro permite recuperar la red con ventaja táctica total.',
    'Chiquita_Ganadora': 'La chiquita ganadora marca diferencias en gestión de alturas y pies del rival.',
    'Bajada_De_Pared': 'La bajada de pared convierte defensa en ataque directo con mucho valor.',
    'Remate_Finalizador': 'El remate finalizador cierra los puntos con autoridad.',
    'Volea_Derecha_Ganadora': 'La volea de derecha ganadora consolida dominio en la red.',
    'Volea_Reves_Ganadora': 'La volea de revés ganadora suma definición y control ofensivo.',
    'Bandeja_Vibora_Definitiva': 'La bandeja o víbora definitiva es un arma real para romper el punto.',
    'Volea_Bloqueo_Contraataque': 'La volea de bloqueo aprovecha la potencia rival para contraatacar.',
    'Dormilona': 'La dormilona aporta variedad y calidad en la resolución cerca de red.',
}
