services:
  web:
    build: .
    image: edvardks-portfolio:prod
    container_name: edvardks-portfolio
    restart: unless-stopped
    ports:
      - "5000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - padel_data:/app/public/padel-data

volumes:
  padel_data:
