services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: iaconedu-db:latest
    image: edvardks-portfolio:prod
    container_name: flask
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      ALLOWED_HOSTS: localhost,127.0.0.1,flask
      SQLITE_DB_PATH: /app/data/db.sqlite3
      PORT: 8000
      GUNICORN_WORKERS: 3
      GUNICORN_TIMEOUT: 60
    ports:
      - "5000:8000"
    volumes:
      - app_data:/app/data

volumes:
  app_data:
